### ISSUE TITLE
Add short paragraph: SBML is for people in http://model.caltech.edu/documents/what-is-sbml/

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-org-website#10]
Currently, there is only a section `SBML is for software` section on http://model.caltech.edu/documents/what-is-sbml/. It would be great if this could be followed by a paragraph `SBML is for people`

**Content in bullet points**
- working in teams is part of science, exchange of information about models is important, SBML is the medium for doing this
- communicating your results and ensuring reproducibility is an important task in modeling, SBML enable this for you
- SBML provides an ecosystem of tools and expertise to make modeling and analysis easier, supporting you in building your models. You will have better models in a faster time.

**Comment by mhucka** [comment]
I took a stab at rewriting the page to add this section. The changes are in commit 1e2a5f7d. They're up on the dev site and the main site.

**Comment by mhucka** [comment]
@matthiaskoenig if you are satisfied with the text (added last year), I will close this issue. Sorry to take so long to get back to this.
