### ISSUE TITLE
meta description tag not descriptive enough

### ISSUE THREAD

**Issue by fbergmann** [sbmlteam/sbml-org-website#12]
It was brought to my attention by @cannin, that the description tag, which right now reads only: 

       <meta name="description" content="SBML Home Page">

he suggests instead to add the first sentence from the wikipedia entry instead. More information: 

<https://moz.com/learn/seo/meta-description>

if possible the same tag should be used for the current page too. (As otherwise the description displayed in google search results for sbml.org is rather empty.)

**Comment by mhucka** [comment]
An excellent point. I will make this change.

**Comment by mhucka** [comment]
Commit f08d301f adds a longer description tag. It will appear on every page of the site. The changes can be previewed at https://model.caltech.edu

**Comment by mhucka** [comment]
I'm going to close this issue but feel free if to reopen it if you find that the new metadata is insufficient.
