### ISSUE TITLE
Link issue tracker on specifications page

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-org-website#14]
Just happend to me. I am reading the specification, found an errata and want to open an issue for that. There is no information on
http://sbml.org/Documents/Specifications
where to report errata or issues with the specifications, but there should be a link on the page.

**Comment by mhucka** [comment]
Revisiting this old issue, I think this problem is solved. The page http://sbml.org/Documents/Specifications has links to trackers for the specs. @matthiaskoenig can you confirm this is what you meant when you filed this issue?

**Comment by matthiaskoenig** [comment]
Yes, this is what I meant. The new site fixed this.
