### ISSUE TITLE
Showcase page not working

### ISSUE THREAD

**Issue by laasfeld** [sbmlteam/sbml-org-website#19]
Hello! At the moment the showcase page (https://sbml.org/facilities/showcase) is not working and giving the "404 page not found" error.

**Comment by mhucka** [comment]
We had to remove the showcase from the site. The information was many years out of date, and people routinely complained to us about how misleading it was. No one on the team has the time or resources to do an update, and we hated to remove it, but removing it altogether was simply the only viable option for the near term. Maybe someday we'll a way to recreate it in a better, more sustainable way.
