### ISSUE TITLE
Add direct github edit links on pages

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-org-website#4]
I find it very helpful to have a direct link of the webpages to the github page. Often done via a small link "edit site on github" on the pages. This allows via a simple click to easily update the markdown. 
At the least a link to the github repository somewhere in the header or footer of the page.

**Comment by mhucka** [comment]
It's a good idea. I will work on this.

**Comment by mhucka** [comment]
I haven't been able to figure out the Hugo syntax to get the path to the current file. So for now, all I could do is add a link to the Github repo top-level directory. This is in commit 109bc9ba.

**Comment by matthiaskoenig** [comment]
@mhucka Perhaps you are looking for the `RelPermalink` property of a page.
See
https://gohugo.io/content-management/page-resources/#properties
and discussion here
https://discourse.gohugo.io/t/how-to-get-the-url-of-the-current-page-with-the-rel-or-relref-function/29113/2

**Comment by mhucka** [comment]
@matthiaskoenig You're right, that was exactly what I needed to know. I've updated the page template now and the bottom right of every page now features "Edit on GitHub".

Thanks again.
