### ISSUE TITLE
Site needs a 404 page

### ISSUE THREAD

**Issue by mhucka** [sbmlteam/sbml-org-website#40]
[As suggested by @matthiaskoenig](https://github.com/sbmlteam/sbml-org-website/issues/33#issuecomment-1149923900) in a comment on issue #33, we need a proper 404 page on sbml.org

**Comment by mhucka** [comment]
OK, there's a new 404 handler on the site. The 404 redirection is handled by the proxy server, and the page template is [this page](https://github.com/sbmlteam/sbml-org-website/blob/main/site/layouts/404.html).

**Comment by matthiaskoenig** [comment]
Thanks this is great.
