### ISSUE TITLE
Links on sbml.org to specifications are broken

### ISSUE THREAD

**Issue by cdiener** [sbmlteam/sbml-org-website#45]
## MRE

Navigate to https://sbml.org/documents/specifications/ and click on any of the "Specification" links. This will give a 404 error on the combine website since addresses like `https://co.mbine.org/specifications/sbml.level-3.version-2.core.release-2` do not exist there.

## Expected behavior

Those links should navigate to the actual spec.

**Comment by mhucka** [comment]
Oh, argh. Thanks for reporting this.
