### ISSUE TITLE
FAQ broken link

### ISSUE THREAD

**Issue by SenorMasFantastico** [sbmlteam/sbml-org-website#54]
FAQ: https://sbml.org/documents/faq/

"As a first step, you can use the [SBML2LaTeX web service](http://sbml.org/Facilities/SBML2LaTeX) to generate a report summarizing the content of an SBML file"

the [SBML2LaTeX web service] is broken: 404 error.

here's the correct URL: http://www.ra.cs.uni-tuebingen.de/software/SBML2LaTeX/

**Comment by matthiaskoenig** [comment]
Thanks for the report.

@SenorMasFantastico You can also use the https://sbml4humans.de service as an alternative (does not create latex but allows to get an overview over the SBML.

**Comment by draeger** [comment]
This webservice was, unfortunately, retired and is no longer available. I suggest replacing the link with two options:
1. The online tool [SBML4humans](https://sbml4humans.de/)
2. The GitHub repository of [SBML2LaTeX](https://github.com/draeger-lab/SBML2LaTeX/)
