### ISSUE TITLE
Icons on landing page should link to details

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-org-website#6]
The icons on the landing page should link to something.
I.e. on https://model.caltech.edu/ clicking on the info icon for instance should link to https://model.caltech.edu/documents/what-is-sbml/
Same for other icons on landing page. First thing I tried to get more info by clicking on the icons when seeing the site.

**Comment by mhucka** [comment]
Originally, I didn't link them because the paragraphs next to the icons mention multiple destinations. But okay, I guess we can pick one and make it a link to the highest-level page that is relevant to the topic described.

This is done in commit dc076ab6.

**Comment by matthiaskoenig** [comment]
Top. This is much better.
