### ISSUE TITLE
Some tests labelled as pass should actually fail

### ISSUE THREAD

**Issue by mhemery** [sbmlteam/sbml-org-website#62]
Am I write to say that the 3 tests :
21101-pass-00-37-sev1-l3v2.xml
21101-pass-00-38-l3v2.xml
21101-pass-00-39-sev1-l3v2.xml

Should actually fail as they constitute of a unique reaction that have neither reactant nor product which is labelled as an error, (see test : 21101-fail-01-01-sev2-l2v1.xml for example).

Sincerely,

**Comment by fbergmann** [comment]
The issue here, is that these files are for Level 3 Version 2 of the SBML specification, where reactions without reactants or products have been allowed. (In fact as general rule for L3V2, is that most requirements have been lifted). 

So this is as it needs to be.
