### ISSUE TITLE
Link the website from this git repository

### ISSUE THREAD

**Issue by matthiaskoenig** [sbmlteam/sbml-org-website#8]
One can add a website link to git repositories which is shown at the top of the github landing page. This makes it very easy to navigate from the git repository to the actual page. 
I saw that some issue was closed, but now I have to lookup in my emails under which url the page is hosted. Much easier to directly have the link in the repository (or at least in the README).

**Comment by draeger** [comment]
Done: http://model.caltech.edu (see GitHub landing page). Thanks for the hint!
